# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
wally = "UpliftGames/wally@0.3.2"
stylua = "johnnymorganz/stylua@0.20.0"
selene = "Kampfkarren/selene@0.27.1"
luau = "JohnnyMorganz/luau-lsp@1.31.0"
