[package]
name = "supersocial/flux"
authors = ["Cody Nelson"]
description = "Flux is a lightweight game framework"
version = "0.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
Signal = "sleitnick/signal@2.0.1"
Comm = "sleitnick/comm@1.0.1"
Trove = "sleitnick/trove@1.1.0"
Symbol = "sleitnick/symbol@2.0.1"
Logr = "cody-nelson/logr@0.0.8"
t = "osyrisrblx/t@3.1.1"
