[package]
name = "supersocial/flux"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
realm = "shared"
description = "Flux is a lightweight game framework"
authors = ["Cody Nelson", "KinqAndi"]

include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"
Signal = "sleitnick/signal@2.0.1"
Comm = "sleitnick/comm@1.0.1"
Symbol = "sleitnick/symbol@2.0.1"
Trove = "cody-nelson/trove@0.0.1"
Logr = "cody-nelson/logr@0.0.8"
t = "cody-nelson/t@1.0.0"